### ISSUE TITLE
not support code block

### ISSUE THREAD

**Issue by dayuyang1999** [tutts/google-sites-markdown#4]

**Comment by tutts** [comment]
Hi @dayuyang1999, I've not thought of that use case, assuming because the string literal backticks are used for the codeblocks.

So you can escape the backticks like so:

```
<script>
markdown`

# Look code blocks!

\`\`\`
<html>
  <div>Look code blocks!</div>
</html>
\`\`\`
`
</script> 
```

Which yields the correct result, but there's no CSS for the `<pre><code /></pre>` so it's not distinguishable against normal text. I'll add something in and update the docs regarding code blocks, thanks for raising the issue 👍

**Comment by tutts** [comment]
Hi @dayuyang1999 I've updated the script, it now has support for code styles and updated the readme.
